services:
  nginx:
    container_name: nginx
    depends_on:
      - backend
    restart: always
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    ports:
      - "80:80"
      - "443:443"
    command: "/bin/sh -c 'while :; do sleep 12h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./quizBE/src/public/uploads:/usr/backend/src/public/uploads
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
  
  certbot:
    container_name: my-certbot
    image: certbot/dns-nsone:v1.18.0
    restart: unless-stopped
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  mysqldb:
    image: mysql:8.0
    container_name: mysqldb
    restart: unless-stopped
    command: --init-file /data/application/init.sql
    volumes:
      - ./quiz.sql:/data/application/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: quiz
    expose:
      - "3306"

  backend:
    container_name: backend
    depends_on:
      - mysqldb
    build:
      context: ./quizBE
    restart: unless-stopped
    expose:
      - "8000"
    environment:
      PORT: 8000
      REACT_URL: https://thibanglaixe.pro.vn
      NODE_ENV: development
      DB_HOST: mysqldb
      DB_PORT: 3306
      DB_USERNAME: root
      DB_PASSWORD: 123456
      DB_DATABASE_NAME: quiz
      DB_DIALECT: mysql
      PRIVATE_KEY_TOKEN: sakdamdiwoanldzns99023129dajsdasdlkamlsd
      EXPIRES_IN_TOKEN: 86400000
      EXPIRES_IN_COOKIES: 86400000
    volumes:
      - ./quizBE/src/public/uploads:/usr/backend/src/public/uploads